# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_treasure_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='img_url',
        ),
        migrations.AddField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default=b'media/default.png', upload_to=b'treasure_images'),
        ),
    ]
